# Generated by Django 4.2.7 on 2023-11-29 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batu_prn", models.CharField(max_length=20, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(max_length=200)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("last_name", models.CharField(max_length=200)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization_name", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=50)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("key_points", models.TextField()),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("c_degree", models.CharField(blank=True, max_length=75, null=True)),
                (
                    "c_department",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("current_year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "current_semester",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "cgpa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("ss_name", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "ss_school_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("ss_start_year", models.DateField(blank=True, null=True)),
                ("ss_end_year", models.DateField(blank=True, null=True)),
                (
                    "ss_marks",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("ps_name", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "ps_school_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("ps_start_year", models.DateField(blank=True, null=True)),
                ("ps_end_year", models.DateField(blank=True, null=True)),
                (
                    "ps_marks",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "designation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "experience_years",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                ("about_me", models.TextField(blank=True, max_length=300, null=True)),
                (
                    "technical_skills",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "soft_skills",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("github", models.URLField(blank=True, null=True)),
                ("linkedin", models.URLField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.student",
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("certificate_name", models.CharField(max_length=250)),
                ("issue_date", models.DateField()),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("link", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("key_points", models.TextField()),
                ("link", models.CharField(max_length=200)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.student",
                    ),
                ),
            ],
        ),
    ]
